[wrong] test: dont exit with 1 wrong: this commit contains intentional issues or reserved a bug from previous commits intentionally in order to test the ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,7 +54,7 @@ jobs:
           if [[ "$script_response" != *"BgUtilScriptPot: Generating POT via script"* ]]; then
             # echo "::error title=BgUtilScriptPot was not invoked::BgUtilScriptPot was not invoked"
             echo "::error file=LICENSE,line=1,endLine=3,title=title::msg“
-            exit 1
+            # exit 1
           fi
       - name: Test server method
         if: always()
@@ -71,6 +71,7 @@ jobs:
           echo $script_response
           if [[ "$script_response" != *"BgUtilHTTPPot: Generating POT via HTTP server"* ]]; then
             # echo "::error title=BgUtilHTTPPot was not invoked::BgUtilHTTPPot was not invoked"
-            echo "::error file=.gitignore,line=1,endLine=3,title=title::msg“
-            exit 1
+            # echo "::error file=.gitignore,line=1,endLine=3,title=title::msg“
+            echo "::error title=ERROR (...),file=/_file,line=1,col=1,endLine=1,endColumn=1::_file:1:1: msg"
+            # exit 1
           fi
