[wrong] format ping result with jq wrong: this commit contains intentional issues or reserved a bug from previous commits intentionally in order to test the ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -49,7 +49,7 @@ jobs:
           cp -aT plugin/ ~/yt-dlp-plugins/bgutil-ytdlp-pot-provider/
       - name: Test script method
         run: |
-          script_response=$(./yt-dlp -vF --print-traffic BaW_jenozKc --extractor-args "youtube:getpot_bgutil_script=server/build/generate_once.js" 2>&1) || echo "::error title=Failed to run yt-dlp::Failed to run yt-dlp!"
+          script_response=$(./yt-dlp -vF --print-traffic BaW_jenozKc --extractor-args "youtube:getpot_bgutil_script=server/build/generate_once.js" 2>&1) || echo "::error title=Failed to run yt-dlp::yt-dlp returned $? exit status"
           echo $script_response
           if [[ "$script_response" != *"BgUtilScriptPot: Generating POT via script"* ]]; then
             echo "BgUtilScriptPot was not invoked"
@@ -64,15 +64,14 @@ jobs:
           node build/main.js&
           cd ..
           echo "Waiting for server to be up..."
-          until curl --silent --fail http://127.0.0.1:4416/ping; do
+          until RESP=$(curl -o- --silent --fail http://127.0.0.1:4416/ping 2>&1); do
             sleep 0.5
           done
-          script_response=$(./yt-dlp -vF --print-traffic BaW_jenozKc --extractor-args "youtube:getpot_bgutil_baseurl=http://127.0.0.1:4416" 2>&1) || echo "::error title=Failed to run yt-dlp::Failed to run yt-dlp!"
+          echo $RESP|jq
+          script_response=$(./yt-dlp -vF --print-traffic BaW_jenozKc --extractor-args "youtube:getpot_bgutil_baseurl=http://127.0.0.1:4416" 2>&1) || echo "::error title=Failed to run yt-dlp::yt-dlp returned $? exit status"
           echo $script_response
           if [[ "$script_response" != *"BgUtilHTTPPot: Generating POT via HTTP server"* ]]; then
             echo "BgUtilHTTPPot was not invoked"
-            echo "::error title=BgUtilHTTPPot was not invoked::BgUtilHTTPPot was not invoked"
-            echo "::error title=BgUtilHTTPPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_http.py,line=1,col=1,endLine=1,endColumn=1::_file:1:1: msg placeholder"
-            echo "::error title=BgUtilHTTPPot was not invoked,file=/plugin/yt_dlp_plugins/extractor/getpot_bgutil_http.py,line=1,col=1,endLine=1,endColumn=1::_file:1:1: msg placeholder2"
+            echo "::error title=BgUtilHTTPPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_http.py,line=1,col=1,endLine=1,endColumn=1::BgUtilHTTPPot was not invoked"
             exit 1
           fi
