[wrong] test github styled output: ::error wrong: this commit contains intentional issues or reserved a bug from previous commits intentionally in order to test the ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,6 +54,7 @@ jobs:
           if [[ "$script_response" != *"BgUtilScriptPot: Generating POT via script"* ]]; then
             echo "BgUtilScriptPot was not invoked"
             echo "::error title=BgUtilScriptPot was not invoked::BgUtilScriptPot was not invoked"
+            exit 1
           fi
       - name: Test server method
         timeout-minutes: 3
@@ -71,4 +72,5 @@ jobs:
           if [[ "$script_response" != *"BgUtilHTTPPot: Generating POT via HTTP server"* ]]; then
             echo "BgUtilHTTPPot was not invoked"
             echo "::error title=BgUtilHTTPPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_http.py,line=1,col=1,endLine=1,endColumn=1::BgUtilHTTPPot was not invoked"
+            echo "::error"
           fi
