[wrong] exit 1, try omitting line/column wrong: this commit contains intentional issues or reserved a bug from previous commits intentionally in order to test the ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -53,7 +53,8 @@ jobs:
           echo $script_response
           if [[ "$script_response" != *"BgUtilScriptPot: Generating POT via script"* ]]; then
             echo "BgUtilScriptPot was not invoked"
-            echo "::error title=BgUtilScriptPot was not invoked::BgUtilScriptPot was not invoked"
+            # echo "::error title=BgUtilScriptPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_script.py,line=1,col=1,endLine=1,endColumn=1::BgUtilScriptPot was not invoked"
+            echo "::error title=BgUtilScriptPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_script.py::BgUtilScriptPot was not invoked"
             exit 1
           fi
       - name: Test server method
@@ -73,5 +74,5 @@ jobs:
           if [[ "$script_response" != *"BgUtilHTTPPot: Generating POT via HTTP server"* ]]; then
             echo "BgUtilHTTPPot was not invoked"
             echo "::error title=BgUtilHTTPPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_http.py,line=1,col=1,endLine=1,endColumn=1::BgUtilHTTPPot was not invoked"
-            echo "::error"
+            exit 1
           fi
