[wrong:for testing] add timer for http server

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,7 +52,8 @@ jobs:
           printf "%s\n" "$script_response"
           echo "::endgroup::"
           if [[ "$script_response" != *"BgUtilScriptPot: Generating POT via script: "* ]]; then
-            echo "::error title=BgUtilScriptPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_script.py::BgUtilScriptPot was not invoked"
+            echo "::error title=BgUtilScriptPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_script.py::" \
+              "BgUtilScriptPot was not invoked"
             exit 1
           fi
       - name: Test server method
@@ -65,17 +66,25 @@ jobs:
           node build/main.js >$SERVER_LOG_PATH 2>&1 &
           NODE_PID=$!
           echo "Waiting for server to be up..."
-          until RESP=$(curl -o- --silent --fail http://127.0.0.1:4416/ping 2>&1); do
-            sleep 0.5
-            # TODO: add timeout (is the step's timeout-minutes enough or should we handle timeout ourselves?)
-          done
+
+          ping() {
+            until RESP=$(curl -o- --silent --fail http://127.0.0.1:4416/ping 2>&1); do
+              sleep ${1:-0.5}
+            done
+          }
+          export -f ping
+          timeout 7.5 bash -c "ping 0.5" || \
+            echo "::error title=Timeout reached,file=server/src/main.ts::" \
+              "Timeout reached before the server is up."
 
           echo "::group::Response from HTTP server"
           echo $RESP | jq
           echo "::endgroup::"
 
           cd ..
-          script_response=$(./yt-dlp -vF --print-traffic BaW_jenozKc 2>&1) || echo "::error title=Failed to run yt-dlp when testing HTTP server::yt-dlp returned $? exit status"
+          script_response=$(./yt-dlp -vF --print-traffic BaW_jenozKc 2>&1) || \
+            echo "::error title=Failed to run yt-dlp when testing HTTP server::" \
+              "yt-dlp returned $? exit status"
 
           kill $NODE_PID
 
@@ -89,6 +98,7 @@ jobs:
           echo "::endgroup::"
 
           if [[ "$script_response" != *"BgUtilHTTPPot: Generating POT via HTTP server"* ]]; then
-            echo "::error title=BgUtilHTTPPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_http.py::BgUtilHTTPPot was not invoked"
+            echo "::error title=BgUtilHTTPPot was not invoked,file=plugin/yt_dlp_plugins/extractor/getpot_bgutil_http.py::" \
+              "BgUtilHTTPPot was not invoked"
             exit 1
           fi
