debug

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -71,9 +71,10 @@ jobs:
           echo "Waiting for server to be up..."
 
           ping() {
-            until curl -o- --silent --fail http://127.0.0.1:4416/ping 2>&1; do
+            until FINAL_RESP=$(curl -o- --silent --fail http://127.0.0.1:4416/ping 2>&1); do
               sleep ${1:-0.5}
             done
+            [ -n "$FINAL_RESP" ] && echo $FINAL_RESP || echo "failed to get ping response"
           }
           export -f ping
           PING_RESP=$(timeout 7.5 bash -c ping) || \
